name: .NET

on:
  push:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/IRPFStonks

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --logger="trx;logfilename=TestResults.Net6.0.trx" --blame-crash --blame-hang-timeout 5m --collect:"XPlat Code Coverage"

    - name: Reporting
      uses: dorny/test-reporter@v1.6.0
      if: success() || failure() # run this step even if previous step failed
      with:
        name: 'Test results report'
        reporter: 'dotnet-trx'
        path: '**/TestResults/TestResults*.trx'
        only-summary: 'true'
        max-annotations: '10'
        fail-on-error: 'true'
        list-suites: 'failed'
        list-tests: 'failed'